#!/usr/bin/env bash

if [ -f ./sail ]; then
    ./sail "$@"
elif [ -d "./vendor/bin" ] && [ -f ./vendor/bin/sail ]; then
    ./vendor/bin/sail "$@"
else
    echo "O script sail não foi encontrado!"
fi

